### ISSUE TITLE
哈希分片，有错误

### ISSUE THREAD

**Issue by langgo** [blogways/blogways.github.io#45]
![image](https://cloud.githubusercontent.com/assets/15521789/17696244/bf742f12-63df-11e6-934d-0635936a84de.png)

![image](https://cloud.githubusercontent.com/assets/15521789/17696252/cb9cfb70-63df-11e6-9a13-c0054522a353.png)

http://www.blogways.net/blog/2015/05/05/mongodb-sharding-introduction-by-docs.html
哈希分片，有错误

**PS：如果，不能保证正确，请不要误人子弟！！！**

**Comment by wanzhou** [comment]
**非常感谢指出我们的错误！翻译不当，见谅！**
